[2024-10-24T06:27:23.351+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extracao.executa_funcao manual__2024-10-24T06:27:12.909130+00:00 [queued]>
[2024-10-24T06:27:23.375+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extracao.executa_funcao manual__2024-10-24T06:27:12.909130+00:00 [queued]>
[2024-10-24T06:27:23.376+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-24T06:27:23.422+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): executa_funcao> on 2024-10-24 06:27:12.909130+00:00
[2024-10-24T06:27:23.432+0000] {standard_task_runner.py:57} INFO - Started process 1861 to run task
[2024-10-24T06:27:23.438+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extracao', 'executa_funcao', 'manual__2024-10-24T06:27:12.909130+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkj06ts4h']
[2024-10-24T06:27:23.449+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask executa_funcao
[2024-10-24T06:27:23.638+0000] {task_command.py:410} INFO - Running <TaskInstance: Extracao.executa_funcao manual__2024-10-24T06:27:12.909130+00:00 [running]> on host cf8624b924b9
[2024-10-24T06:27:23.970+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='Victor' AIRFLOW_CTX_DAG_ID='Extracao' AIRFLOW_CTX_TASK_ID='executa_funcao' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T06:27:12.909130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T06:27:12.909130+00:00'
[2024-10-24T06:27:24.045+0000] {logging_mixin.py:150} INFO - Registro {'id': 1, 'nome': 'Alice Silva', 'email': 'alice.silva@email.com', 'telefone': '(11) 98765-4321', 'data_nascimento': '1990-05-12', 'sexo': 'Feminino', 'cidade': 'São Paulo', 'estado': 'SP', '_id': ObjectId('6719e8cc3f2e334117c36e5d')} já existe no banco de dados.
[2024-10-24T06:27:24.050+0000] {logging_mixin.py:150} INFO - Registro {'id': 2, 'nome': 'Bob Oliveira', 'email': 'bob.oliveira@email.com', 'telefone': '(21) 97654-3210', 'data_nascimento': '1985-08-23', 'sexo': 'Masculino', 'cidade': 'Rio de Janeiro', 'estado': 'RJ', '_id': ObjectId('6719e8cc3f2e334117c36e5e')} já existe no banco de dados.
[2024-10-24T06:27:24.056+0000] {logging_mixin.py:150} INFO - Registro {'id': 3, 'nome': 'Carla Santos', 'email': 'carla.santos@email.com', 'telefone': '(31) 96543-2109', 'data_nascimento': '1992-12-01', 'sexo': 'Feminino', 'cidade': 'Belo Horizonte', 'estado': 'MG', '_id': ObjectId('6719e8cc3f2e334117c36e5f')} já existe no banco de dados.
[2024-10-24T06:27:24.065+0000] {logging_mixin.py:150} INFO - Registro {'id': 4, 'nome': 'Daniel Costa', 'email': 'daniel.costa@email.com', 'telefone': '(41) 95432-1098', 'data_nascimento': '1988-03-15', 'sexo': 'Masculino', 'cidade': 'Curitiba', 'estado': 'PR', '_id': ObjectId('6719e8cc3f2e334117c36e60')} já existe no banco de dados.
[2024-10-24T06:27:24.072+0000] {logging_mixin.py:150} INFO - Registro {'id': 5, 'nome': 'Elena Martins', 'email': 'elena.martins@email.com', 'telefone': '(51) 94321-0987', 'data_nascimento': '1995-07-30', 'sexo': 'Feminino', 'cidade': 'Porto Alegre', 'estado': 'RS', '_id': ObjectId('6719e8cc3f2e334117c36e61')} já existe no banco de dados.
[2024-10-24T06:27:24.074+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 27, in extracao
    print(f"Processo de inserção concluído {pd.__version_}.")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute '__version_'
[2024-10-24T06:27:24.094+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extracao, task_id=executa_funcao, execution_date=20241024T062712, start_date=20241024T062723, end_date=20241024T062724
[2024-10-24T06:27:24.143+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 83 for task executa_funcao (module 'pandas' has no attribute '__version_'; 1861)
[2024-10-24T06:27:24.176+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-24T06:27:24.231+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
